# Generated by Django 5.0.6 on 2026-06-23 22:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS negocio;",
            reverse_sql="DROP SCHEMA IF EXISTS negocio CASCADE;",
        ),
        migrations.CreateModel(
            name='QuoteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('config_type', models.CharField(choices=[('print_location', 'Ubicación de estampado'), ('print_size', 'Tamaño de estampado')], max_length=50, verbose_name='config type')),
                ('label', models.CharField(help_text='Ej: Pecho, Espalda, Manga / Pequeño, Mediano, Grande', max_length=100, verbose_name='label')),
                ('extra_cost', models.DecimalField(decimal_places=2, help_text='Costo adicional que se suma al precio base de la polera', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='extra cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Configuración de cotización',
                'verbose_name_plural': 'Configuraciones de cotización',
                'db_table': 'negocio"."quote_configs',
                'unique_together': {('config_type', 'label')},
            },
        ),
    ]
